[project]
name            = "dockerwatch"
version         = "0.1.0"
description     = "Add your description here"
readme          = "README.md"
requires-python = ">=3.13"
dependencies    = [
    "black>=25.1.0",
    "docker>=7.1.0",
 "dotenv>=0.9.9",
 "rich>=14.0.0",
]
